import assert from 'node:assert/strict';
import {buildBaseline,conflictKeys,mergeSnapshots,clocksEqual,meaningfulCount,vaultFingerprint,forceState} from '../assets/js/sync-merge-v260.mjs';
const STORES=['patients','appointments','records'];
const vault={salt:'s',iterations:600000,version:3};
const snap=(patients=[],appointments=[],records=[],tombs=[])=>({format:'rm-local-backup',version:4,meta:{vault,schemaVersion:5,syncTombstones:tombs},stores:{patients,appointments,records}});
const base=snap([{id:'p1',updatedAt:'2026-08-10T10:00:00Z'}]);
const remote=snap([{id:'p1',updatedAt:'2026-08-10T11:00:00Z'}]);
const local=snap([{id:'p1',updatedAt:'2026-08-10T10:00:00Z'}],[{id:'a1',patientId:'p1',updatedAt:'2026-08-10T10:30:00Z'}]);
const baseline=buildBaseline(base,STORES);
assert.deepEqual(conflictKeys(local,remote,baseline,STORES),[],'alterações em lados distintos não devem gerar conflito');
const merged=mergeSnapshots(local,remote,STORES,()=> '2026-08-10T12:00:00Z');
assert.equal(merged.stores.patients[0].updatedAt,'2026-08-10T11:00:00Z');
assert.equal(merged.stores.appointments.length,1);
assert.equal(meaningfulCount(merged),2);
assert.equal(vaultFingerprint(merged),'s:600000:3');
const bothLocal=snap([{id:'p1',updatedAt:'2026-08-10T11:10:00Z'}]);
const bothRemote=snap([{id:'p1',updatedAt:'2026-08-10T11:20:00Z'}]);
assert.deepEqual(conflictKeys(bothLocal,bothRemote,baseline,STORES),['patients:p1'],'mudança bilateral deve pausar merge automático');
const resolved=mergeSnapshots(bothLocal,bothRemote,STORES);forceState(resolved,bothLocal,'patients:p1',STORES,{touchAt:'2026-08-10T12:30:00Z'});assert.equal(resolved.stores.patients[0].updatedAt,'2026-08-10T12:30:00Z');
const deleted=snap([],[],[],[{storeName:'patients',id:'p1',deletedAt:'2026-08-10T13:00:00Z'}]);
const deletionMerged=mergeSnapshots(remote,deleted,STORES);assert.equal(deletionMerged.stores.patients.length,0,'tombstone mais novo deve vencer registro antigo');
assert.equal(clocksEqual(remote,remote,STORES),true);
console.log('private-sync-v260: 9 assertions passed');
