from __future__ import annotations

import json
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

REPOS = {
    "geral": "Rastreioclinico",
    "tdah": "rastreioTDAH",
    "bipolar": "tab-bateria-integrada",
    "borderline": "Inventario-de-Tracos-Borderline",
    "narcisismo": "bateria.narcisismo",
    "impulsividade": "Rastreio-de-Impulsividade",
    "esquemas": "rastreio.de.esquemas",
    "modos": "rastreiomodosesquematicos",
    "necessidades": "Escala-de-Necessidades-Emocionais",
    "codependencia": "Escala-de-Co-Depenpencia-Emocional",
    "icaps": "ICAPS",
    "risco": "TriagemRiscoSuicidio",
    "monitoramentos": "Inicio-de-Jornada-Terapeutica",
}

PATTERNS = {
    "whatsapp_result_channel": re.compile(r"\bwa\.me\b|api\.whatsapp|\bwhatsapp\b", re.I),
    "browser_clinical_storage": re.compile(r"\blocalStorage\b|\bsessionStorage\b|\bindexedDB\b", re.I),
    "firebase_or_firestore": re.compile(r"\bfirebase\b|\bfirestore\b|\baddDoc\s*\(|\bsetDoc\s*\(", re.I),
    "patient_result_ui": re.compile(r"id=[\"']results?[\"']|class=[\"'][^\"']*\bresult(?:ado|ados|s)?\b[^\"']*[\"']|\bresultados?\b", re.I),
    "client_scorer": re.compile(r"\bcalculateScore\b|\bcalcularPontu|\btotalScore\b|\bpercentil\b|\bpercentile\b|\bscore\s*[=:]", re.I),
    "diagnostic_priming": re.compile(r"\bDSM-?5\b|\btranstorno\b|\bdiagn[oó]stic|\bquadro cl[ií]nico\b|\bborderline\b|\bnarcis|\bbipolar\b|\bTDAH\b|\bsuic[ií]d", re.I),
    "splash_or_loader": re.compile(r"(?:id|class)\s*=\s*[\"'][^\"']*(?:\bsplash\b|\bpreloader\b|\bloading-screen\b|\bloader-wrapper\b)[^\"']*[\"']|\bpreloader\b|\bloading-screen\b|\bloader-wrapper\b", re.I),
    "google_form_surface": re.compile(r"docs\.google\.com/forms|forms\.gle|\bgoogleform\b", re.I),
    "hardcoded_email": re.compile(r"\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b", re.I),
    "dev_residue": re.compile(r"\bTODO\b|\bFIXME\b|generated by ai|\bchatgpt\b|system prompt|developer instruction", re.I),
}

IGNORE_PARTS = {".git", ".github", "node_modules", "tests", "test", "scripts", "dist", "vendor"}
EXTENSIONS = {".html", ".htm", ".js", ".mjs", ".css", ".json"}


def clone(repo: str, dest: Path) -> None:
    subprocess.run(
        ["git", "clone", "--depth", "1", "--quiet", f"https://github.com/ricmurtapsicologia/{repo}.git", str(dest)],
        check=True,
        timeout=60,
    )


def scan(root: Path) -> dict:
    counts = {key: 0 for key in PATTERNS}
    files = {key: set() for key in PATTERNS}
    scanned = 0
    for path in root.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in EXTENSIONS:
            continue
        if any(part in IGNORE_PARTS for part in path.relative_to(root).parts):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        scanned += 1
        rel = str(path.relative_to(root))
        for key, pattern in PATTERNS.items():
            matches = pattern.findall(text)
            if matches:
                counts[key] += len(matches)
                files[key].add(rel)
    markers = {
        key: {"count": counts[key], "files": sorted(files[key])}
        for key in PATTERNS
        if counts[key]
    }
    risk_weight = {
        "whatsapp_result_channel": 4,
        "browser_clinical_storage": 5,
        "firebase_or_firestore": 5,
        "patient_result_ui": 3,
        "client_scorer": 4,
        "diagnostic_priming": 2,
        "splash_or_loader": 1,
        "google_form_surface": 3,
        "hardcoded_email": 4,
        "dev_residue": 2,
    }
    score = sum(min(counts[k], 5) * risk_weight[k] for k in counts)
    return {"scannedFiles": scanned, "markerScore": score, "markers": markers}


def main() -> None:
    report = {
        "schemaVersion": "1.1.0",
        "purpose": "Static source-residue inventory only; marker presence is not proof of patient exposure or clinical validity.",
        "scope": "public frontend source files; workflows/tests/scripts excluded",
        "instruments": {},
    }
    tmp_root = Path(tempfile.mkdtemp(prefix="screening-residue-"))
    try:
        for instrument_id, repo in REPOS.items():
            dest = tmp_root / repo
            entry = {"repository": f"ricmurtapsicologia/{repo}", "cloneState": "OK"}
            try:
                clone(repo, dest)
                entry.update(scan(dest))
            except Exception as exc:
                entry.update({"cloneState": "FAILED", "errorType": type(exc).__name__})
            report["instruments"][instrument_id] = entry
    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)

    ranked = sorted(
        (
            {"id": key, "repository": value["repository"], "markerScore": value.get("markerScore", -1)}
            for key, value in report["instruments"].items()
        ),
        key=lambda x: (x["markerScore"], x["id"]),
    )
    report["rankedSimplestFirstByStaticMarkerScore"] = ranked
    out = Path("rastreios/pipeline/source-residue-audit.json")
    out.write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
